import Head from 'next/head';
import ExampleCard from '../components/cards/example/ExampleCard';
import { mockExampleCardProps } from '../components/cards/example/ExampleCard.mocks';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-gradient-to-r from-cyan-500 to-blue-500">
          <h1 className="">
            Welcome To <a href="https://next.org">Next.js!</a>
          </h1>
          <ExampleCard {...mockExampleCardProps.base} />
        </div>
      </main>
    </div>
  );
};

export default Home;

Home.getLayout = (page) => {
  return <PrimaryLayout>{page}</PrimaryLayout>;
};
